# Generated by Zero
import typing  # remove this if not needed
from typing import List, Dict, Union, Optional, Tuple  # remove this if not needed
from consolemenu import *
from consolemenu.items import *
from zero import ZeroClient


zero_client = ZeroClient("localhost", 8888)


class RpcClient:
    def __init__(self, zero_client: ZeroClient):
        self._zero_client = zero_client

    def echo(self, msg: str) -> str:
        return self._zero_client.call("echo", msg)

    def hello_world(self) -> str:
        return self._zero_client.call("hello_world", None)


def menu():
    menu = ConsoleMenu("SportClient v999")
    menu.show()


if __name__ == "__main__":
    rpc_client = RpcClient(zero_client)
    menu()
